/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface GuestbookInterface extends Interface {
    getFunction(nameOrSignature: "entries" | "writeMessage"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "NewEntry"): EventFragment;

    encodeFunctionData(functionFragment: 'entries', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'writeMessage', values: [string]): string;

    decodeFunctionResult(functionFragment: 'entries', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'writeMessage', data: BytesLike): Result;
  }

  
    export namespace NewEntryEvent {
      export type InputTuple = [writer: AddressLike, message: string, timestamp: BigNumberish];
      export type OutputTuple = [writer: string, message: string, timestamp: bigint];
      export interface OutputObject {writer: string, message: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Guestbook extends BaseContract {
    
    connect(runner?: ContractRunner | null): Guestbook;
    waitForDeployment(): Promise<this>;

    interface: GuestbookInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    entries: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint] & {writer: string, message: string, timestamp: bigint }],
      'view'
    >
    

    
    writeMessage: TypedContractMethod<
      [_message: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'entries'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint] & {writer: string, message: string, timestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'writeMessage'): TypedContractMethod<
      [_message: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'NewEntry'): TypedContractEvent<NewEntryEvent.InputTuple, NewEntryEvent.OutputTuple, NewEntryEvent.OutputObject>;

    filters: {
      
      'NewEntry(address,string,uint256)': TypedContractEvent<NewEntryEvent.InputTuple, NewEntryEvent.OutputTuple, NewEntryEvent.OutputObject>;
      NewEntry: TypedContractEvent<NewEntryEvent.InputTuple, NewEntryEvent.OutputTuple, NewEntryEvent.OutputObject>;
    
    };
  }