/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Guestbook } from './Guestbook.js';
export * as factories from './factories/index.js';
export { Guestbook__factory } from './factories/Guestbook__factory.js';