/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Guestbook } from "./Guestbook";
export * as factories from "./factories";
export { Guestbook__factory } from "./factories/Guestbook__factory";
